name: Push Commit Every Month

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  monthly_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Ayush Thakur"
          git config --global user.email "iamayushthakur9@gmail.com"

      - name: Make and push dummy commit
        run: |
          echo "Automated commit on $(date)" > monthly_commit_log.txt
          git add monthly_commit_log.txt
          git commit -m "Automated monthly commit [skip ci]"
      
      - name: Push changes
        run: |
          git pull && git push origin HEAD:main